### ISSUE TITLE
Finalize control panel

### ISSUE THREAD

**Issue by dahaynes** [dahaynes/SOLAP#28]
The control panel consists of the following parts
1. Chatbot: Text
2. Time period: Slider
3. Geographic Unit: Radio controls

I want this control to be in a fixed location in a separate Div from the filter control accordions. When the accordions open and you need to scroll, the control panel is not affected.

**Comment by DelandPo** [comment]
This is fixed https://github.com/dahaynes/SOLAP/pull/29

**Comment by dahaynes** [comment]
Good work
